### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by chewiebug** [chewiebug/berry#1]
- [ ] I'd be willing to implement a fix

**Describe the bug**

**To Reproduce**

The _minimal_ information needed to reproduce your issue (ideally a package.json with a single dep). Note that bugs without minimal reproductions might be closed.

IMPORTANT: We strongly prefer reproductions that use Sherlock. Please check our documentation for more information: https://yarnpkg.com/advanced/sherlock

```js repro
const { promises: fs } = require('fs')

// doesn't matter, where the proxy constants point - error always occurs
const YARNRC_YAML = `
httpProxy: "http://localhost:8881"
httpsProxy: "http://localhost:8881"
`

await fs.writeFile('.yarnrc.yml', YARNRC_YAML)

await expect(packageJsonAndInstall({
  dependencies: {
    "lodash": "4.17.15"
  },
})).rejects.not.toThrow()
```
dd

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...]
 - Node version [e.g. 8.15.0, 10.15.1, ...]
 - Yarn version [e.g. 2.0.0-rc1, ...]

**Additional context**

**Comment by chewiebug** [comment]
```js repro
const { promises: fs } = require('fs')

// doesn't matter, where the proxy constants point - error always occurs
const YARNRC_YAML = `
httpProxy: "http://localhost:8881"
httpsProxy: "http://localhost:8881"
`

await fs.writeFile('.yarnrc.yml', YARNRC_YAML)

await expect(packageJsonAndInstall({
  dependencies: {
    "lodash": "4.17.15"
  },
})).rejects.not.toThrow()
```

**Comment by chewiebug** [comment]
This issue reproduces on master:
```
Error: expect(received).rejects.not.toThrow()

Error name:    "Error"
Error message: "Command failed: /usr/bin/node /github/workspace/scripts/actions/../run-yarn.js install
/github/workspace/.yarn/cache/yoga-layout-prebuilt-npm-1.9.3-b527507fd5-2.zip/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: options.request.emit is not a function
    at ClientRequest.onError (/github/workspace/.yarn/cache/tunnel-npm-0.0.6-b1c0830ea4-2.zip/node_modules/tunnel/lib/tunnel.js:183:21)
    at Object.onceWrapper (events.js:313:26)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketErrorListener (_http_client.js:415:9)
    at Socket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

➤ YN0000: ┌ Resolution step
::group::Resolution step
"

      at ClientRequest.onError (../../github/workspace/.yarn/cache/tunnel-npm-0.0.6-b1c0830ea4-2.zip/node_modules/tunnel/lib/tunnel.js:183:21)
      ➤ YN0000: ┌ Resolution step
      ::group::Resolution step
    at Object.toThrow (/github/workspace/.yarn/cache/expect-npm-24.8.0-8c7640c562-2.zip/node_modules/expect/build/index.js:242:20)
    at module.exports (evalmachine.<anonymous>:16:17)
    at async /github/workspace/.yarn/cache/@arcanis-sherlock-npm-1.0.38-d4f5e2dbf3-2.zip/node_modules/@arcanis/sherlock/lib/executeRepro.js:56:13
    at async executeInTempDirectory (/github/workspace/.yarn/cache/@arcanis-sherlock-npm-1.0.38-d4f5e2dbf3-2.zip/node_modules/@arcanis/sherlock/lib/executeRepro.js:17:16)
    at async Object.executeRepro (/github/workspace/.yarn/cache/@arcanis-sherlock-npm-1.0.38-d4f5e2dbf3-2.zip/node_modules/@arcanis/sherlock/lib/executeRepro.js:24:12)
    at async ExecCommand.execute (/github/workspace/.yarn/cache/@arcanis-sherlock-npm-1.0.38-d4f5e2dbf3-2.zip/node_modules/@arcanis/sherlock/lib/commands/exec.js:25:38)
    at async ExecCommand.validateAndExecute (/github/workspace/.yarn/cache/clipanion-npm-2.0.0-rc.16-b9444aaf89-2.zip/node_modules/clipanion/lib/advanced/Command.js:161:26)
    at async Cli.run (/github/workspace/.yarn/cache/clipanion-npm-2.0.0-rc.16-b9444aaf89-2.zip/node_modules/clipanion/lib/advanced/Cli.js:74:24)
    at async Cli.runExit (/github/workspace/.yarn/cache/clipanion-npm-2.0.0-rc.16-b9444aaf89-2.zip/node_modules/clipanion/lib/advanced/Cli.js:83:28)
```

**Comment by chewiebug** [comment]
does anything happen, if I continue to comment?

**Comment by chewiebug** [comment]
```js repro
const { promises: fs } = require('fs')

// doesn't matter, where the proxy constants point - error always occurs
const YARNRC_YAML = `
httpProxy: "http://localhost:8881"
httpsProxy: "http://localhost:8881"
`

await fs.writeFile('.yarnrc.yml', YARNRC_YAML)

await expect(packageJsonAndInstall({
  dependencies: {
    "lodash": "4.17.15"
  },
})).rejects.not.toThrow()
```
